---
# Config file for OCP GA 4.3 stable channel minus 1 version

RUN:
  client_version: '4.3-ga'

DEPLOYMENT:
  ocp_url_template: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{version}/{file_name}-{os_type}-{version}.tar.gz"
  installer_version: "4.3-ga"
  terraform_version: "0.11.14"
  ocp_channel: "stable"
  ocp_version_index: -2
ENV_DATA:
  vm_template: 'rhcos-4.4.3-x86_64-vmware.x86_64'
  # rhcos_ami: 'ami-06c85f9d106577272'
  # If rhcos_ami is not specified the ID for aws upi deployments will be fetched from
  # https://raw.githubusercontent.com/openshift/installer/release-4.4/data/data/rhcos.json
