---
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: olmcontentsourcepolicy
spec:
  repositoryDigestMirrors:
  # WA for issue: https://github.com/red-hat-storage/ocs-ci/issues/4038
  - mirrors:
    - brew.registry.redhat.io/rh-osbs/openshift/ose-local-storage-operator
    source: registry.redhat.io/openshift4/ose-local-storage-operator
  # End of WA
  - mirrors:
    - brew.registry.redhat.io
    source: registry.redhat.io
  - mirrors:
    - brew.registry.redhat.io
    source: registry.stage.redhat.io
  - mirrors:
    - brew.registry.redhat.io
    source: registry-proxy.engineering.redhat.com

---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: optional-operators
  namespace: openshift-marketplace
spec:
  displayName: Optional operators
  icon:
    base64data: ""
    mediatype: ""
  image: quay.io/openshift-qe-optional-operators/ocp4-index:latest
  publisher: Red Hat
  sourceType: grpc
